MOBILE VERSION SKELETON
Goodluck5956/mobile-skeleton pull request #1
Opened 2021-08-16 16:15 UTC by Goodluck5956

1.  The necessary tools were installed for a bug-free project
2. The header section has the menu-top, which consists of the logo and the hamburger menu.
3. The body section has the biography which consists of the introductory part
4. The footer section consists of the media navigation link.
5. The project was styled using CSS.

2021-08-16 18:12 UTC, barackm requested changes
Hi @Goodluck5956 , 👋 

You have done an amazing job so far! 👏👏👏
However, there are some issues that you still need to work on to go to the next project. But remember you are almost there 😉  😉 !

# STATUS: Required Changes ♻️

- [ ] Kindly let's start with uppercase letters while writing commit messages

### _Check the comments under the review._ 👇 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] [OPTIONAL] I think having a name like **mobile-skeleton** for a repository isn't a good idea, because this seems to be like a branch name instead. This is actually your portfolio website, so giving the repository a name like **personal-portfolio** or **portfolio** could make more sense. 😉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-16 18:12 UTC, barackm commented on README.md
> +Deployment
- [ ] It seems that you are talking about the different steps we need to follow in order to get the local copy of the project, but you don't show any of those steps. Can you please add those steps so that non-technical people may understand what you are talking about 👍

2021-08-16 23:25 UTC, Emmyn5600 requested changes
## STATUS: CHANGES REQUESTED :recycle:

Hi, @Goodluck5956 

Great work on implementing the changes requested by the previous reviewer, however there are some issues to be solved before you get approved but you are almost there:muscle:

Changes required :writing_hand:  
      
   - Please check the comment under the review. 
   
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-08-16 23:25 UTC, Emmyn5600 commented on index.html
> +    <title>Set up and mobile version skeleton</title>
- [ ]  Let us use the descriptive title for our project, for example use your full names.

2021-08-16 23:25 UTC, Emmyn5600 commented on index.html
> +        </header>
- [ ] Let us add indentation for the `nav tag` as well as arrange our `header tag` properly. 
- [ ] Kindly, fix the menu button as required, seem to be broken as you can check on the below image.
![port12](https://user-images.githubusercontent.com/55635977/129640858-7e042530-20bf-43ba-b763-fe74f33fd104.png)

2021-08-16 23:25 UTC, Emmyn5600 commented on index.html
> +            </ul>
- [ ] Again, fix the social media icons, seem to broken again, check the assets folder to fix that issue.
![port13](https://user-images.githubusercontent.com/55635977/129640994-d164a36c-6896-4bdb-944c-85d3086e4f93.png)

2021-08-16 23:25 UTC, Emmyn5600 commented on style.css
> +
- [ ] Kindly, remove the overflow-x in the mobile view section for the UX purpose, hint: Use `overflow-x:hidden` 
![port14](https://user-images.githubusercontent.com/55635977/129641214-5c4b1077-b37b-4c7d-b142-720cf1a40ff9.png)

2021-08-17 10:13 UTC, mke2111 approved these changes
### Hi @Goodluck5956, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
**Congratulations! 🎉** 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-17 14:12 UTC, merged